"""Basic generator mapping."""

from melodica.generators import (
    MelodyGenerator,
    ArpeggiatorGenerator,
    BassGenerator,
    ChordGenerator,
    OstinatoGenerator,
    StrumPatternGenerator,
    PercussionGenerator,
    RiffGenerator,
    GrooveGenerator,
    PianoRunGenerator,
    DyadGenerator,
    AmbientPadGenerator,
    ViolinGenerator,
    ViolaGenerator,
    CelloGenerator,
    ContrabassGenerator,
    HarpGenerator,
    OrchestralScoreGenerator,
    FluteGenerator,
    OboeGenerator,
    ClarinetGenerator,
    BassoonGenerator,
    TrumpetGenerator,
    TromboneGenerator,
    FrenchHornGenerator,
    TimpaniGenerator,
    MalletPercussionGenerator,
    FilmScoreGenerator,
    OrchestralTransitionGenerator,
    TubaGenerator,
    SnareDrumGenerator,
    OrchestralCymbalGenerator,
    TubularBellsGenerator,
    TanpuraGenerator,
    SitarGenerator,
    TablaGenerator,
    OudGenerator,
    NeyGenerator,
    DarbukaGenerator,
    SaxophoneSectionGenerator,
    FlugelhornGenerator,
    EnglishHornGenerator,
    BassClarinetGenerator,
    VibraphoneGenerator,
    PedalSteelGenerator,
    DobroLapSteelGenerator,
    FiddleGenerator,
    ErhuGenerator,
    ShamisenGenerator,
    KotoGenerator,
    BandoneonGenerator,
    WoodwindSoloGenerator,
    GlassHarpGenerator,
    HandPanGenerator,
    ThereminGenerator,
    VocalScatGenerator,
    GregorianChantGenerator,
    MusetteAccordionGenerator,
    EuphoniumGenerator,
    AltoFluteGenerator,
    KalimbaGenerator,
    ShakerGenerator,
    WindMachineGenerator,
    ConcertBassDrumGenerator,
)

BASIC_GENERATORS = {
    "melody": lambda p, cfg: MelodyGenerator(
        params=p,
        harmony_note_probability=cfg.get("harmony_note_probability", 0.64),
        note_range_low=cfg.get("note_range_low"),
        note_range_high=cfg.get("note_range_high"),
    ),
    "arpeggiator": lambda p, cfg: ArpeggiatorGenerator(
        params=p,
        pattern=cfg.get("pattern", "up"),
        note_duration=cfg.get("note_duration", 0.25),
    ),
    "bass": lambda p, cfg: BassGenerator(
        params=p,
        allowed_notes=cfg.get("allowed_notes", ["root", "fourth"]),
        global_movement=cfg.get("global_movement", "none"),
        note_movement=cfg.get("note_movement", "alternating"),
    ),
    "chord": lambda p, cfg: ChordGenerator(
        params=p,
        voicing=cfg.get("voicing", "open"),
    ),
    "ostinato": lambda p, cfg: OstinatoGenerator(
        params=p,
        pattern=cfg.get("pattern", "1-3-5-3"),
    ),
    "strum": lambda p, cfg: StrumPatternGenerator(
        params=p,
        voicing=cfg.get("voicing", "guitar"),
        pattern_name=cfg.get("pattern_name", "folk"),
    ),
    "percussion": lambda p, cfg: PercussionGenerator(
        params=p,
        pattern_name=cfg.get("pattern_name", "rock"),
    ),
    "riff": lambda p, cfg: RiffGenerator(
        params=p,
        scale_type=cfg.get("scale_type", "minor_pent"),
        riff_pattern=cfg.get("riff_pattern", "gallop"),
    ),
    "groove": lambda p, cfg: GrooveGenerator(
        params=p,
        groove_pattern=cfg.get("groove_pattern", "funk_1"),
    ),
    "piano_run": lambda p, cfg: PianoRunGenerator(
        params=p,
        technique=cfg.get("technique", "straddle"),
        notes_per_run=cfg.get("notes_per_run", 8),
    ),
    "dyads": lambda p, cfg: DyadGenerator(
        params=p,
        interval_pref=cfg.get("interval_pref", [3, 4, 7]),
        motion_mode=cfg.get("motion_mode", "parallel"),
    ),
    "ambient": lambda p, cfg: AmbientPadGenerator(
        params=p,
        voicing=cfg.get("voicing", "spread"),
        overlap=cfg.get("overlap", 0.5),
    ),
    "violin": lambda p, cfg: ViolinGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", True),
        con_sordino=cfg.get("con_sordino", False),
        double_stops=cfg.get("double_stops", False),
        position=cfg.get("position", 1),
    ),
    "viola": lambda p, cfg: ViolaGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", True),
        con_sordino=cfg.get("con_sordino", False),
        double_stops=cfg.get("double_stops", False),
        position=cfg.get("position", 1),
    ),
    "cello": lambda p, cfg: CelloGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", True),
        con_sordino=cfg.get("con_sordino", False),
        double_stops=cfg.get("double_stops", False),
        position=cfg.get("position", 1),
        bass_voice=cfg.get("bass_voice", False),
    ),
    "contrabass": lambda p, cfg: ContrabassGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", False),
        con_sordino=cfg.get("con_sordino", False),
        position=cfg.get("position", 1),
        bass_voice=cfg.get("bass_voice", True),
    ),
    "harp": lambda p, cfg: HarpGenerator(
        params=p,
        pattern=cfg.get("pattern", "arpeggio"),
        direction=cfg.get("direction", "up"),
        spread_speed=cfg.get("spread_speed", 0.125),
        octave_span=cfg.get("octave_span", 3),
        glissando_scale=cfg.get("glissando_scale", "diatonic"),
    ),
    "orchestral_score": lambda p, cfg: OrchestralScoreGenerator(
        params=p,
        sections=cfg.get("sections", []),
        texture=cfg.get("texture", "full"),
        include_choir=cfg.get("include_choir", True),
        include_harp=cfg.get("include_harp", True),
        include_brass=cfg.get("include_brass", True),
    ),
    "flute": lambda p, cfg: FluteGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", True),
        register=cfg.get("register", 2),
    ),
    "oboe": lambda p, cfg: OboeGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", True),
        register=cfg.get("register", 2),
    ),
    "clarinet": lambda p, cfg: ClarinetGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", False),
        register=cfg.get("register", 2),
        bass_voice=cfg.get("bass_voice", False),
    ),
    "bassoon": lambda p, cfg: BassoonGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", False),
        register=cfg.get("register", 1),
    ),
    "trumpet": lambda p, cfg: TrumpetGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        con_sordino=cfg.get("con_sordino", False),
        register=cfg.get("register", 2),
        fanfare_mode=cfg.get("fanfare_mode", False),
    ),
    "trombone": lambda p, cfg: TromboneGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        con_sordino=cfg.get("con_sordino", False),
        register=cfg.get("register", 2),
        bass_voice=cfg.get("bass_voice", False),
    ),
    "french_horn": lambda p, cfg: FrenchHornGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        con_sordino=cfg.get("con_sordino", False),
        register=cfg.get("register", 2),
    ),
    "timpani": lambda p, cfg: TimpaniGenerator(
        params=p,
        stroke_pattern=cfg.get("stroke_pattern", "single"),
        drum_count=cfg.get("drum_count", 4),
        tuning_follows=cfg.get("tuning_follows", True),
        roll_speed=cfg.get("roll_speed", 0.125),
    ),
    "mallet": lambda p, cfg: MalletPercussionGenerator(
        params=p,
        instrument=cfg.get("instrument", "marimba"),
        pattern=cfg.get("pattern", "arpeggio"),
        mallet_count=cfg.get("mallet_count", 2),
    ),
    "film_score": lambda p, cfg: FilmScoreGenerator(
        params=p,
        hit_points=cfg.get("hit_points", []),
        emotional_arcs=cfg.get("emotional_arcs", []),
        default_mood=cfg.get("default_mood", "calm"),
        include_choir=cfg.get("include_choir", True),
        include_brass=cfg.get("include_brass", True),
        include_harp=cfg.get("include_harp", True),
    ),
    "orchestral_transition": lambda p, cfg: OrchestralTransitionGenerator(
        params=p,
        transition_type=cfg.get("transition_type", "crescendo_build"),
        intensity_curve=cfg.get("intensity_curve", "crescendo"),
    ),
    "tuba": lambda p, cfg: TubaGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        mute=cfg.get("mute", False),
        growl=cfg.get("growl", False),
    ),
    "snare_drum": lambda p, cfg: SnareDrumGenerator(
        params=p,
        pattern_type=cfg.get("pattern_type", "march"),
    ),
    "orchestral_cymbal": lambda p, cfg: OrchestralCymbalGenerator(
        params=p,
        pattern_type=cfg.get("pattern_type", "crash"),
    ),
    "tubular_bells": lambda p, cfg: TubularBellsGenerator(
        params=p,
        stroke_pattern=cfg.get("stroke_pattern", "single"),
        dampen=cfg.get("dampen", False),
    ),
    "tanpura": lambda p, cfg: TanpuraGenerator(
        params=p,
        tuning=cfg.get("tuning", "Sa-Pa"),
        jivari=cfg.get("jivari", 0.5),
        pluck_pattern=cfg.get("pluck_pattern", "standard"),
    ),
    "sitar_v2": lambda p, cfg: SitarGenerator(
        params=p,
        sympathetic_resonance=cfg.get("sympathetic_resonance", 0.4),
        meend_probability=cfg.get("meend_probability", 0.35),
        krintan_probability=cfg.get("krintan_probability", 0.25),
    ),
    "tabla": lambda p, cfg: TablaGenerator(
        params=p,
        tala=cfg.get("tala", "teental"),
        bayan_modulation=cfg.get("bayan_modulation", 0.5),
        humanize_swing=cfg.get("humanize_swing", 0.05),
    ),
    "oud": lambda p, cfg: OudGenerator(
        params=p,
        tremolo_density=cfg.get("tremolo_density", 0.3),
        risha_style=cfg.get("risha_style", "standard"),
        chorus_detune=cfg.get("chorus_detune", 0.1),
    ),
    "ney": lambda p, cfg: NeyGenerator(
        params=p,
        breath_noise=cfg.get("breath_noise", 0.4),
        vibrato_depth=cfg.get("vibrato_depth", 0.3),
        legato_glide=cfg.get("legato_glide", 0.25),
    ),
    "darbuka": lambda p, cfg: DarbukaGenerator(
        params=p,
        rhythm_pattern=cfg.get("rhythm_pattern", "maqsoum"),
        rolls_probability=cfg.get("rolls_probability", 0.2),
    ),
    "sax_section": lambda p, cfg: SaxophoneSectionGenerator(
        params=p,
        voicing_style=cfg.get("voicing_style", "block"),
        baritone_doubles_lead=cfg.get("baritone_doubles_lead", True),
        velocity_spread=cfg.get("velocity_spread", 8),
    ),
    "flugelhorn": lambda p, cfg: FlugelhornGenerator(
        params=p,
        breath_vibrato=cfg.get("breath_vibrato", True),
    ),
    "english_horn": lambda p, cfg: EnglishHornGenerator(
        params=p,
        vibrato=cfg.get("vibrato", True),
    ),
    "bass_clarinet": lambda p, cfg: BassClarinetGenerator(
        params=p,
    ),
    "vibraphone": lambda p, cfg: VibraphoneGenerator(
        params=p,
        pattern=cfg.get("pattern", "warm_chords"),
        motor_speed_hz=cfg.get("motor_speed_hz", 6.0),
        pedal=cfg.get("pedal", True),
    ),
    "pedal_steel": lambda p, cfg: PedalSteelGenerator(
        params=p,
        slide_speed=cfg.get("slide_speed", 0.2),
        volume_swell=cfg.get("volume_swell", True),
    ),
    "dobro": lambda p, cfg: DobroLapSteelGenerator(
        params=p,
        scoop_depth=cfg.get("scoop_depth", 1.5),
        vibrato_depth=cfg.get("vibrato_depth", 0.25),
    ),
    "fiddle": lambda p, cfg: FiddleGenerator(
        params=p,
        double_stop_probability=cfg.get("double_stop_probability", 0.4),
        open_string_drone=cfg.get("open_string_drone", True),
        slide_probability=cfg.get("slide_probability", 0.3),
    ),
    "erhu": lambda p, cfg: ErhuGenerator(
        params=p,
        glide_probability=cfg.get("glide_probability", 0.4),
        vibrato_depth=cfg.get("vibrato_depth", 0.3),
    ),
    "shamisen": lambda p, cfg: ShamisenGenerator(
        params=p,
        sawari_buzz=cfg.get("sawari_buzz", 0.4),
        strike_velocity=cfg.get("strike_velocity", 80),
    ),
    "koto": lambda p, cfg: KotoGenerator(
        params=p,
        tremolo_probability=cfg.get("tremolo_probability", 0.25),
        double_pluck=cfg.get("double_pluck", True),
    ),
    "shakuhachi": lambda p, cfg: WoodwindSoloGenerator(
        params=p,
        instrument="shakuhachi",
        breath_vibrato=cfg.get("breath_vibrato", True),
    ),
    "bandoneon": lambda p, cfg: BandoneonGenerator(
        params=p,
        bellows_accents=cfg.get("bellows_accents", 0.5),
    ),
    "glass_harp": lambda p, cfg: GlassHarpGenerator(
        params=p,
        friction_noise=cfg.get("friction_noise", 0.3),
    ),
    "handpan": lambda p, cfg: HandPanGenerator(
        params=p,
        strike_damping=cfg.get("strike_damping", 0.5),
    ),
    "theremin": lambda p, cfg: ThereminGenerator(
        params=p,
        vibrato_speed=cfg.get("vibrato_speed", 6.0),
        vibrato_depth=cfg.get("vibrato_depth", 0.4),
    ),
    "vocal_scat": lambda p, cfg: VocalScatGenerator(
        params=p,
        scat_complexity=cfg.get("scat_complexity", 0.5),
    ),
    "gregorian_chant": lambda p, cfg: GregorianChantGenerator(
        params=p,
        reverb_presence=cfg.get("reverb_presence", 0.7),
    ),
    "musette": lambda p, cfg: MusetteAccordionGenerator(
        params=p,
        detune_cents=cfg.get("detune_cents", 15.0),
    ),
    "euphonium": lambda p, cfg: EuphoniumGenerator(
        params=p,
        note_density=cfg.get("note_density", 1.0),
    ),
    "alto_flute": lambda p, cfg: AltoFluteGenerator(
        params=p,
        breath_vibrato=cfg.get("breath_vibrato", True),
        note_density=cfg.get("note_density", 1.0),
    ),
    "kalimba_solo": lambda p, cfg: KalimbaGenerator(
        params=p,
        pop_intensity=cfg.get("pop_intensity", 0.5),
        note_density=cfg.get("note_density", 1.0),
    ),
    "shaker": lambda p, cfg: ShakerGenerator(
        params=p,
        instrument=cfg.get("instrument", "shaker"),
        rhythm_style=cfg.get("rhythm_style", "16th"),
        note_density=cfg.get("note_density", 1.0),
    ),
    "wind_machine": lambda p, cfg: WindMachineGenerator(
        params=p,
        effect_type=cfg.get("effect_type", "wind"),
        intensity_curve=cfg.get("intensity_curve", "swell"),
        note_density=cfg.get("note_density", 1.0),
    ),
    "concert_bass_drum": lambda p, cfg: ConcertBassDrumGenerator(
        params=p,
        drum_type=cfg.get("drum_type", "bass_drum"),
        pattern_type=cfg.get("pattern_type", "roll"),
        roll_subdivision=cfg.get("roll_subdivision", 0.125),
    ),
}

