"""Basic generator mapping."""

from melodica.generators import (
    MelodyGenerator,
    ArpeggiatorGenerator,
    BassGenerator,
    ChordGenerator,
    OstinatoGenerator,
    StrumPatternGenerator,
    PercussionGenerator,
    RiffGenerator,
    GrooveGenerator,
    PianoRunGenerator,
    DyadGenerator,
    AmbientPadGenerator,
    ViolinGenerator,
    ViolaGenerator,
    CelloGenerator,
    ContrabassGenerator,
    HarpGenerator,
    OrchestralScoreGenerator,
    FluteGenerator,
    OboeGenerator,
    ClarinetGenerator,
    BassoonGenerator,
    TrumpetGenerator,
    TromboneGenerator,
    FrenchHornGenerator,
    TimpaniGenerator,
    MalletPercussionGenerator,
)

BASIC_GENERATORS = {
    "melody": lambda p, cfg: MelodyGenerator(
        params=p,
        harmony_note_probability=cfg.get("harmony_note_probability", 0.64),
        note_range_low=cfg.get("note_range_low"),
        note_range_high=cfg.get("note_range_high"),
    ),
    "arpeggiator": lambda p, cfg: ArpeggiatorGenerator(
        params=p,
        pattern=cfg.get("pattern", "up"),
        note_duration=cfg.get("note_duration", 0.25),
    ),
    "bass": lambda p, cfg: BassGenerator(
        params=p,
        allowed_notes=cfg.get("allowed_notes", ["root", "fourth"]),
        global_movement=cfg.get("global_movement", "none"),
        note_movement=cfg.get("note_movement", "alternating"),
    ),
    "chord": lambda p, cfg: ChordGenerator(
        params=p,
        voicing=cfg.get("voicing", "open"),
    ),
    "ostinato": lambda p, cfg: OstinatoGenerator(
        params=p,
        pattern=cfg.get("pattern", "1-3-5-3"),
    ),
    "strum": lambda p, cfg: StrumPatternGenerator(
        params=p,
        voicing=cfg.get("voicing", "guitar"),
        pattern_name=cfg.get("pattern_name", "folk"),
    ),
    "percussion": lambda p, cfg: PercussionGenerator(
        params=p,
        pattern_name=cfg.get("pattern_name", "rock"),
    ),
    "riff": lambda p, cfg: RiffGenerator(
        params=p,
        scale_type=cfg.get("scale_type", "minor_pent"),
        riff_pattern=cfg.get("riff_pattern", "gallop"),
    ),
    "groove": lambda p, cfg: GrooveGenerator(
        params=p,
        groove_pattern=cfg.get("groove_pattern", "funk_1"),
    ),
    "piano_run": lambda p, cfg: PianoRunGenerator(
        params=p,
        technique=cfg.get("technique", "straddle"),
        notes_per_run=cfg.get("notes_per_run", 8),
    ),
    "dyads": lambda p, cfg: DyadGenerator(
        params=p,
        interval_pref=cfg.get("interval_pref", [3, 4, 7]),
        motion_mode=cfg.get("motion_mode", "parallel"),
    ),
    "ambient": lambda p, cfg: AmbientPadGenerator(
        params=p,
        voicing=cfg.get("voicing", "spread"),
        overlap=cfg.get("overlap", 0.5),
    ),
    "violin": lambda p, cfg: ViolinGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", True),
        con_sordino=cfg.get("con_sordino", False),
        double_stops=cfg.get("double_stops", False),
        position=cfg.get("position", 1),
    ),
    "viola": lambda p, cfg: ViolaGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", True),
        con_sordino=cfg.get("con_sordino", False),
        double_stops=cfg.get("double_stops", False),
        position=cfg.get("position", 1),
    ),
    "cello": lambda p, cfg: CelloGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", True),
        con_sordino=cfg.get("con_sordino", False),
        double_stops=cfg.get("double_stops", False),
        position=cfg.get("position", 1),
        bass_voice=cfg.get("bass_voice", False),
    ),
    "contrabass": lambda p, cfg: ContrabassGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", False),
        con_sordino=cfg.get("con_sordino", False),
        position=cfg.get("position", 1),
        bass_voice=cfg.get("bass_voice", True),
    ),
    "harp": lambda p, cfg: HarpGenerator(
        params=p,
        pattern=cfg.get("pattern", "arpeggio"),
        direction=cfg.get("direction", "up"),
        spread_speed=cfg.get("spread_speed", 0.125),
        octave_span=cfg.get("octave_span", 3),
        glissando_scale=cfg.get("glissando_scale", "diatonic"),
    ),
    "orchestral_score": lambda p, cfg: OrchestralScoreGenerator(
        params=p,
        sections=cfg.get("sections", []),
        texture=cfg.get("texture", "full"),
        include_choir=cfg.get("include_choir", True),
        include_harp=cfg.get("include_harp", True),
        include_brass=cfg.get("include_brass", True),
    ),
    "flute": lambda p, cfg: FluteGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", True),
        register=cfg.get("register", 2),
    ),
    "oboe": lambda p, cfg: OboeGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", True),
        register=cfg.get("register", 2),
    ),
    "clarinet": lambda p, cfg: ClarinetGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", False),
        register=cfg.get("register", 2),
        bass_voice=cfg.get("bass_voice", False),
    ),
    "bassoon": lambda p, cfg: BassoonGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        vibrato=cfg.get("vibrato", False),
        register=cfg.get("register", 1),
    ),
    "trumpet": lambda p, cfg: TrumpetGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        con_sordino=cfg.get("con_sordino", False),
        register=cfg.get("register", 2),
        fanfare_mode=cfg.get("fanfare_mode", False),
    ),
    "trombone": lambda p, cfg: TromboneGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        con_sordino=cfg.get("con_sordino", False),
        register=cfg.get("register", 2),
        bass_voice=cfg.get("bass_voice", False),
    ),
    "french_horn": lambda p, cfg: FrenchHornGenerator(
        params=p,
        articulation=cfg.get("articulation", "sustained"),
        dynamic_curve=cfg.get("dynamic_curve", "flat"),
        con_sordino=cfg.get("con_sordino", False),
        register=cfg.get("register", 2),
    ),
    "timpani": lambda p, cfg: TimpaniGenerator(
        params=p,
        stroke_pattern=cfg.get("stroke_pattern", "single"),
        drum_count=cfg.get("drum_count", 4),
        tuning_follows=cfg.get("tuning_follows", True),
        roll_speed=cfg.get("roll_speed", 0.125),
    ),
    "mallet": lambda p, cfg: MalletPercussionGenerator(
        params=p,
        instrument=cfg.get("instrument", "marimba"),
        pattern=cfg.get("pattern", "arpeggio"),
        mallet_count=cfg.get("mallet_count", 2),
    ),
}
