"""Genre and style-specific generator mapping (A–F)."""

from melodica.generators import (
    BoogieWoogieGenerator,
    StridePianoGenerator,
    TremoloPickingGenerator,
    TangoGenerator,
    ReggaeSkankGenerator,
    MontunoGenerator,
    AcciaccaturaGenerator,
    PedalBassGenerator,
    RagtimeGenerator,
    PowerChordGenerator,
    BrokenChordGenerator,
    PedalMelodyGenerator,
    BeatRepeatGenerator,
    TremoloStringsGenerator,
    PolyrhythmGenerator,
    WaltzGenerator,
    ChoraleGenerator,
    NebulaGenerator,
    HarmonicsGenerator,
    BendGenerator,
    ClusterGenerator,
    CadenceGenerator,
)

GENRE_A_F = {
    "boogie_woogie": lambda p, cfg: BoogieWoogieGenerator(
        params=p,
        pattern=cfg.get("pattern", "standard"),
        octave_bass=cfg.get("octave_bass", True),
        swing=cfg.get("swing", 0.67),
    ),
    "stride_piano": lambda p, cfg: StridePianoGenerator(
        params=p,
        pattern=cfg.get("pattern", "standard"),
        bass_octave_doubled=cfg.get("bass_octave_doubled", True),
        chord_voicing=cfg.get("chord_voicing", "closed"),
    ),
    "tremolo_picking": lambda p, cfg: TremoloPickingGenerator(
        params=p,
        variant=cfg.get("variant", "single"),
        speed=cfg.get("speed", 0.125),
        palm_mute_probability=cfg.get("palm_mute_probability", 0.0),
        note_strategy=cfg.get("note_strategy", "chord_root"),
    ),
    "tango": lambda p, cfg: TangoGenerator(
        params=p,
        pattern=cfg.get("pattern", "marcato"),
        accent=cfg.get("accent", 1.15),
        staccato_chords=cfg.get("staccato_chords", True),
    ),
    "reggae_skank": lambda p, cfg: ReggaeSkankGenerator(
        params=p,
        variant=cfg.get("variant", "skank"),
        staccato=cfg.get("staccato", True),
        mute_probability=cfg.get("mute_probability", 0.1),
    ),
    "montuno": lambda p, cfg: MontunoGenerator(
        params=p,
        pattern=cfg.get("pattern", "son"),
        clave_type=cfg.get("clave_type", "none"),
        octave_doubling=cfg.get("octave_doubling", True),
        tumbao_bass=cfg.get("tumbao_bass", False),
        dynamic_pattern=cfg.get("dynamic_pattern", False),
    ),
    "acciaccatura": lambda p, cfg: AcciaccaturaGenerator(
        params=p,
        grace_type=cfg.get("grace_type", "lower"),
        grace_duration=cfg.get("grace_duration", 0.08),
        main_duration=cfg.get("main_duration", 0.75),
        interval=cfg.get("interval", 0),
        density=cfg.get("density", 0.7),
    ),
    "pedal_bass": lambda p, cfg: PedalBassGenerator(
        params=p,
        pedal_note=cfg.get("pedal_note", "root"),
        sustain=cfg.get("sustain", 0.0),
        velocity_level=cfg.get("velocity_level", 0.8),
    ),
    "ragtime": lambda p, cfg: RagtimeGenerator(
        params=p,
        pattern=cfg.get("pattern", "classic"),
        melody_density=cfg.get("melody_density", 0.8),
        left_hand=cfg.get("left_hand", True),
        right_hand=cfg.get("right_hand", True),
        chromatic_approach=cfg.get("chromatic_approach", True),
    ),
    "power_chord": lambda p, cfg: PowerChordGenerator(
        params=p,
        pattern=cfg.get("pattern", "chug"),
        include_octave=cfg.get("include_octave", True),
        palm_mute_ratio=cfg.get("palm_mute_ratio", 0.6),
    ),
    "broken_chord": lambda p, cfg: BrokenChordGenerator(
        params=p,
        pattern=cfg.get("pattern", "chopin"),
        subdivision=cfg.get("subdivision", 0.25),
        voice_lead=cfg.get("voice_lead", True),
        velocity_envelope=cfg.get("velocity_envelope", "arch"),
    ),
    "pedal_melody": lambda p, cfg: PedalMelodyGenerator(
        params=p,
        pedal_pc=cfg.get("pedal_pc"),
        melody_style=cfg.get("melody_style", "stepwise"),
        melody_rhythm=cfg.get("melody_rhythm", 0.5),
    ),
    "beat_repeat": lambda p, cfg: BeatRepeatGenerator(
        params=p,
        repeat_type=cfg.get("repeat_type", "accelerate"),
        stutter_length=cfg.get("stutter_length", 2.0),
        pitch_shift=cfg.get("pitch_shift", False),
    ),
    "tremolo_strings": lambda p, cfg: TremoloStringsGenerator(
        params=p,
        variant=cfg.get("variant", "chord"),
        bow_speed=cfg.get("bow_speed", 0.0625),
        dynamic_swell=cfg.get("dynamic_swell", True),
    ),
    "polyrhythm": lambda p, cfg: PolyrhythmGenerator(
        params=p,
        ratio=cfg.get("ratio", "3x2"),
        stream_a_pitch=cfg.get("stream_a_pitch", "chord_root"),
        stream_b_pitch=cfg.get("stream_b_pitch", "fifth"),
    ),
    "waltz": lambda p, cfg: WaltzGenerator(
        params=p,
        variant=cfg.get("variant", "viennese"),
        include_bass_octave=cfg.get("include_bass_octave", True),
        staccato_chords=cfg.get("staccato_chords", True),
    ),
    "chorale": lambda p, cfg: ChoraleGenerator(
        params=p,
        voice_spacing=cfg.get("voice_spacing", 12),
        soprano_motion=cfg.get("soprano_motion", "stepwise"),
        rhythmic_unit=cfg.get("rhythmic_unit", 1.0),
    ),
    "nebula": lambda p, cfg: NebulaGenerator(
        params=p,
        variant=cfg.get("variant", "cloud"),
        density_notes=cfg.get("density_notes", 5),
        pitch_spread=cfg.get("pitch_spread", 12),
        note_duration=cfg.get("note_duration", 3.0),
    ),
    "harmonics": lambda p, cfg: HarmonicsGenerator(
        params=p,
        harmonic_type=cfg.get("harmonic_type", "natural"),
        use_chord_tones=cfg.get("use_chord_tones", True),
        duration_per_note=cfg.get("duration_per_note", 2.0),
    ),
    "bend": lambda p, cfg: BendGenerator(
        params=p,
        bend_type=cfg.get("bend_type", "bend_up"),
        bend_range=cfg.get("bend_range", 2),
        bend_speed=cfg.get("bend_speed", 0.06),
    ),
    "clusters": lambda p, cfg: ClusterGenerator(
        params=p,
        cluster_type=cfg.get("cluster_type", "second"),
        cluster_width=cfg.get("cluster_width", 3),
        duration_per_cluster=cfg.get("duration_per_cluster", 2.0),
    ),
    "cadence": lambda p, cfg: CadenceGenerator(
        params=p,
        cadence_type=cfg.get("cadence_type", "PAC"),
        voice_count=cfg.get("voice_count", 4),
        cadence_length=cfg.get("cadence_length", 2.0),
    ),
}
