"""Genre and style-specific generator mapping (G–P)."""

from melodica.generators import (
    SynthBassGenerator,
    SupersawPadGenerator,
    PluckSequenceGenerator,
    StringsLegatoGenerator,
    StringsPizzicatoGenerator,
    BrassSectionGenerator,
    SaxSoloGenerator,
    TrapDrumsGenerator,
    FourOnFloorGenerator,
    BreakbeatGenerator,
    FXRiserGenerator,
    FXImpactGenerator,
    ReharmonizationGenerator,
    ModalInterchangeGenerator,
    VocalChopsGenerator,
    VocalOohsGenerator,
    GuitarLegatoGenerator,
    GuitarTappingGenerator,
    ArrangerGenerator,
    HumanizerGenerator,
    PianoCompGenerator,
    OrganDrawbarsGenerator,
    KeysArpeggioGenerator,
    GuitarStrummingGenerator,
    BassSlapGenerator,
    GuitarSweepGenerator,
    VocalMelismaGenerator,
    VocalAdlibsGenerator,
    ChoirAahsGenerator,
    DrumKitPatternGenerator,
    PercussionEnsembleGenerator,
    ElectronicDrumsGenerator,
    WoodwindsEnsembleGenerator,
    StringsEnsembleGenerator,
    OrchestralHitGenerator,
    LeadSynthGenerator,
    SidechainPumpGenerator,
)

GENRE_G_P = {
    "synth_bass": lambda p, cfg: SynthBassGenerator(
        params=p,
        waveform=cfg.get("waveform", "acid"),
        pattern=cfg.get("pattern", "acid_line"),
        slide_probability=cfg.get("slide_probability", 0.3),
    ),
    "supersaw_pad": lambda p, cfg: SupersawPadGenerator(
        params=p,
        variant=cfg.get("variant", "trance"),
        voice_count=cfg.get("voice_count", 5),
        sidechain_feel=cfg.get("sidechain_feel", False),
    ),
    "pluck_sequence": lambda p, cfg: PluckSequenceGenerator(
        params=p,
        pattern=cfg.get("pattern", "offbeat"),
        decay_time=cfg.get("decay_time", 0.3),
    ),
    "strings_legato": lambda p, cfg: StringsLegatoGenerator(
        params=p,
        section_size=cfg.get("section_size", "ensemble"),
        portamento_speed=cfg.get("portamento_speed", 0.15),
        dynamic_shape=cfg.get("dynamic_shape", "cresc_dim"),
        interval_preference=cfg.get("interval_preference", "step"),
    ),
    "strings_pizzicato": lambda p, cfg: StringsPizzicatoGenerator(
        params=p,
        pattern=cfg.get("pattern", "ostinato"),
        staccato_length=cfg.get("staccato_length", 0.15),
        velocity_variation=cfg.get("velocity_variation", 0.3),
    ),
    "brass_section": lambda p, cfg: BrassSectionGenerator(
        params=p,
        articulation=cfg.get("articulation", "hit"),
        voicing=cfg.get("voicing", "closed"),
        intensity=cfg.get("intensity", 0.8),
    ),
    "sax_solo": lambda p, cfg: SaxSoloGenerator(
        params=p,
        style=cfg.get("style", "bebop"),
        vibrato_depth=cfg.get("vibrato_depth", 0.3),
        chromaticism=cfg.get("chromaticism", 0.5),
    ),
    "trap_drums": lambda p, cfg: TrapDrumsGenerator(
        params=p,
        variant=cfg.get("variant", "standard"),
        hat_roll_density=cfg.get("hat_roll_density", 0.5),
        kick_pattern=cfg.get("kick_pattern", "standard"),
    ),
    "four_on_floor": lambda p, cfg: FourOnFloorGenerator(
        params=p,
        variant=cfg.get("variant", "house"),
        hihat_style=cfg.get("hihat_style", "mixed"),
        swing=cfg.get("swing", 0.0),
    ),
    "breakbeat": lambda p, cfg: BreakbeatGenerator(
        params=p,
        variant=cfg.get("variant", "amen"),
        chop_probability=cfg.get("chop_probability", 0.3),
        ghost_notes=cfg.get("ghost_notes", True),
        double_time=cfg.get("double_time", False),
    ),
    "fx_riser": lambda p, cfg: FXRiserGenerator(
        params=p,
        riser_type=cfg.get("riser_type", "synth"),
        length_beats=cfg.get("length_beats", 4.0),
        pitch_curve=cfg.get("pitch_curve", "exponential"),
    ),
    "fx_impact": lambda p, cfg: FXImpactGenerator(
        params=p,
        impact_type=cfg.get("impact_type", "boom"),
        tail_length=cfg.get("tail_length", 2.0),
        pitch_drop=cfg.get("pitch_drop", 12),
    ),
    "reharmonization": lambda p, cfg: ReharmonizationGenerator(
        params=p,
        strategy=cfg.get("strategy", "tritone"),
        preservation=cfg.get("preservation", "melody"),
        substitution_frequency=cfg.get("substitution_frequency", 0.5),
    ),
    "modal_interchange": lambda p, cfg: ModalInterchangeGenerator(
        params=p,
        source_mode=cfg.get("source_mode", "minor"),
        frequency=cfg.get("frequency", 0.3),
    ),
    "vocal_chops": lambda p, cfg: VocalChopsGenerator(
        params=p,
        processing=cfg.get("processing", "pitch_shift"),
        density=cfg.get("density", 0.6),
        chop_pattern=cfg.get("chop_pattern", "syncopated"),
    ),
    "vocal_oohs": lambda p, cfg: VocalOohsGenerator(
        params=p,
        syllable=cfg.get("syllable", "ooh"),
        harmony_count=cfg.get("harmony_count", 3),
        vibrato=cfg.get("vibrato", 0.4),
    ),
    "guitar_legato": lambda p, cfg: GuitarLegatoGenerator(
        params=p,
        direction=cfg.get("direction", "ascending"),
        notes_per_string=cfg.get("notes_per_string", 4),
        speed=cfg.get("speed", 0.125),
    ),
    "guitar_tapping": lambda p, cfg: GuitarTappingGenerator(
        params=p,
        pattern=cfg.get("pattern", "arpeggio"),
        width_interval=cfg.get("width_interval", 12),
    ),
    "arranger": lambda p, cfg: ArrangerGenerator(
        params=p,
        form=cfg.get("form", "verse_chorus"),
        section_length=cfg.get("section_length", 8),
        variation_seed=cfg.get("variation_seed", 0),
    ),
    "humanizer": lambda p, cfg: HumanizerGenerator(
        params=p,
        timing_variance=cfg.get("timing_variance", 0.03),
        velocity_variance=cfg.get("velocity_variance", 0.1),
        groove_type=cfg.get("groove_type", "straight"),
    ),
    "piano_comp": lambda p, cfg: PianoCompGenerator(
        params=p,
        comp_style=cfg.get("comp_style", "jazz"),
        voicing_type=cfg.get("voicing_type", "shell"),
        accent_pattern=cfg.get("accent_pattern", "syncopated"),
    ),
    "organ_drawbars": lambda p, cfg: OrganDrawbarsGenerator(
        params=p,
        registration=cfg.get("registration", "jazz"),
        leslie_speed=cfg.get("leslie_speed", "slow"),
        percussion=cfg.get("percussion", False),
    ),
    "keys_arpeggio": lambda p, cfg: KeysArpeggioGenerator(
        params=p,
        arp_pattern=cfg.get("arp_pattern", "up"),
        rate=cfg.get("rate", 0.125),
        octave_spread=cfg.get("octave_spread", 2),
    ),
    "guitar_strumming": lambda p, cfg: GuitarStrummingGenerator(
        params=p,
        strum_pattern=cfg.get("strum_pattern", "folk"),
        palm_mute_ratio=cfg.get("palm_mute_ratio", 0.2),
        dead_strums=cfg.get("dead_strums", True),
    ),
    "bass_slap": lambda p, cfg: BassSlapGenerator(
        params=p,
        slap_pattern=cfg.get("slap_pattern", "funky"),
        ghost_note_prob=cfg.get("ghost_note_prob", 0.3),
        pop_probability=cfg.get("pop_probability", 0.4),
    ),
    "guitar_sweep": lambda p, cfg: GuitarSweepGenerator(
        params=p,
        sweep_direction=cfg.get("sweep_direction", "up"),
        note_count=cfg.get("note_count", 5),
        speed=cfg.get("speed", 0.08),
    ),
    "vocal_melisma": lambda p, cfg: VocalMelismaGenerator(
        params=p,
        style=cfg.get("style", "rnb"),
        run_length=cfg.get("run_length", 4),
        vibrato_depth=cfg.get("vibrato_depth", 0.3),
    ),
    "vocal_adlibs": lambda p, cfg: VocalAdlibsGenerator(
        params=p,
        density_adlib=cfg.get("density_adlib", 0.3),
        register=cfg.get("register", "mid"),
        style=cfg.get("style", "adlib"),
    ),
    "choir_ahhs": lambda p, cfg: ChoirAahsGenerator(
        params=p,
        voice_count=cfg.get("voice_count", 4),
        dynamics=cfg.get("dynamics", "mf"),
        vibrato=cfg.get("vibrato", 0.3),
    ),
    "drum_kit_pattern": lambda p, cfg: DrumKitPatternGenerator(
        params=p,
        style=cfg.get("style", "rock"),
        hihat_pattern=cfg.get("hihat_pattern", "eighth"),
        fill_frequency=cfg.get("fill_frequency", 0.2),
    ),
    "percussion_ensemble": lambda p, cfg: PercussionEnsembleGenerator(
        params=p,
        instruments=cfg.get("instruments", ["conga", "bongo", "shaker", "tambourine"]),
        density=cfg.get("density", 0.6),
    ),
    "electronic_drums": lambda p, cfg: ElectronicDrumsGenerator(
        params=p,
        kit=cfg.get("kit", "909"),
        pattern=cfg.get("pattern", "four_on_floor"),
        sidechain=cfg.get("sidechain", False),
    ),
    "woodwinds_ensemble": lambda p, cfg: WoodwindsEnsembleGenerator(
        params=p,
        section=cfg.get("section", "quartet"),
        articulation=cfg.get("articulation", "legato"),
    ),
    "strings_ensemble": lambda p, cfg: StringsEnsembleGenerator(
        params=p,
        section_size=cfg.get("section_size", "full"),
        articulation=cfg.get("articulation", "sustained"),
        divisi=cfg.get("divisi", 4),
    ),
    "orchestral_hit": lambda p, cfg: OrchestralHitGenerator(
        params=p,
        hit_type=cfg.get("hit_type", "staccato"),
        voicing=cfg.get("voicing", "chord"),
        duration=cfg.get("duration", 0.5),
    ),
    "lead_synth": lambda p, cfg: LeadSynthGenerator(
        params=p,
        style=cfg.get("style", "trance"),
        portamento=cfg.get("portamento", 0.15),
        vibrato_depth=cfg.get("vibrato_depth", 0.2),
    ),
    "sidechain_pump": lambda p, cfg: SidechainPumpGenerator(
        params=p,
        rate=cfg.get("rate", "1/4"),
        depth=cfg.get("depth", 0.7),
    ),
}
