"""Genre and style-specific generator mapping (Q–Z) and advanced techniques."""

from melodica.generators import (
    VoiceLeadingGenerator,
    CounterpointGenerator,
    MotifDevelopmentGenerator,
    FilterSweepGenerator,
    EuclideanRhythmGenerator,
    BassWobbleGenerator,
    LoFiHipHopGenerator,
    AfrobeatsGenerator,
    PhonkGenerator,
    MelodicRapGenerator,
    UKGarageGenerator,
    HyperpopGenerator,
    AdvancedStepSequencer,
    BPMAdaptiveGenerator,
    GenreFusionEngine,
    VocalMelodyAutoGenerator,
    JerseyClubGenerator,
    DembowGenerator,
    BaileFunkGenerator,
    RageBeatGenerator,
    PluggnbGenerator,
    LatinTrapGenerator,
    CloudRapGenerator,
    DnBJungleGenerator,
    HardstyleGenerator,
    SynthwaveGenerator,
    BoomBapGenerator,
    FutureBassGenerator,
    GrimeGenerator,
    WitchHouseGenerator,
    PhonkHouseGenerator,
    AmapianoLogDrumGenerator,
    AfroPercussionGenerator,
    HighlifeGuitarGenerator,
    AfroHouseGenerator,
    GqomGenerator,
    KuduroGenerator,
    AfroDrillGenerator,
    CombatEscalationGenerator,
    StingerGenerator,
    ChiptuneGenerator,
    HorrorDissonanceGenerator,
    StealthStateGenerator,
    ProceduralExplorationGenerator,
    BossBattleGenerator,
    PuzzleLoopGenerator,
    MedievalTavernGenerator,
    SciFiUnderscoreGenerator,
    VictoryFanfareGenerator,
    StringsStaccatoGenerator,
    HemiolaGenerator,
    BackbeatGenerator,
    ChordVoicingGenerator,
    DynamicsCurveGenerator,
    SecondaryDominantGenerator,
    SectionBuilderGenerator,
    TransitionGenerator,
    SwingGenerator,
    DownbeatRestGenerator,
    DarkPadGenerator,
    TensionGenerator,
    DarkBassGenerator,
    Bass808SlidingGenerator,
    HiHatStutterGenerator,
    DrillPatternGenerator,
    GhostNotesGenerator,
)

GENRE_Q_Z_ADV = {
    # Advanced composition
    "voice_leading": lambda p, cfg: VoiceLeadingGenerator(
        params=p,
        voices=cfg.get("voices", 4),
        prefer_stepwise=cfg.get("prefer_stepwise", True),
        range_style=cfg.get("range_style", "close"),
    ),
    "counterpoint": lambda p, cfg: CounterpointGenerator(
        params=p,
        species=cfg.get("species", 1),
        voices=cfg.get("voices", 2),
        cantus_position=cfg.get("cantus_position", "below"),
    ),
    "motif_development": lambda p, cfg: MotifDevelopmentGenerator(
        params=p,
        transformations=cfg.get("transformations", ["original", "inversion", "retrograde"]),
        motif_length=cfg.get("motif_length", 4),
        development_style=cfg.get("development_style", "sequential"),
    ),
    "filter_sweep": lambda p, cfg: FilterSweepGenerator(
        params=p,
        sweep_type=cfg.get("sweep_type", "lowpass_open"),
        resonance=cfg.get("resonance", 0.5),
        duration=cfg.get("duration", 4.0),
    ),
    "euclidean_rhythm": lambda p, cfg: EuclideanRhythmGenerator(
        params=p,
        pulses=cfg.get("pulses", 5),
        steps=cfg.get("steps", 8),
        pitch=cfg.get("pitch", "chord_root"),
    ),
    "bass_wobble": lambda p, cfg: BassWobbleGenerator(
        params=p,
        wobble_rate=cfg.get("wobble_rate", "1/8"),
        waveform=cfg.get("waveform", "saw"),
        lfo_shape=cfg.get("lfo_shape", "sine"),
        pitch_slide=cfg.get("pitch_slide", False),
    ),
    # Genres Q–Z
    "lofi_hiphop": lambda p, cfg: LoFiHipHopGenerator(
        params=p,
        variant=cfg.get("variant", "chill"),
        swing_ratio=cfg.get("swing_ratio", 0.62),
        chord_voicing=cfg.get("chord_voicing", "ninth"),
        include_drums=cfg.get("include_drums", True),
        include_bass=cfg.get("include_bass", True),
        vinyl_noise=cfg.get("vinyl_noise", 0.3),
        tape_stop=cfg.get("tape_stop", 0.1),
    ),
    "afrobeats": lambda p, cfg: AfrobeatsGenerator(
        params=p,
        variant=cfg.get("variant", "afrobeats"),
        log_drum_density=cfg.get("log_drum_density", 0.6),
        shaker_pattern=cfg.get("shaker_pattern", "sixteenth"),
        include_piano=cfg.get("include_piano", True),
        bounce_amount=cfg.get("bounce_amount", 0.5),
        percussion_layer=cfg.get("percussion_layer", True),
    ),
    "phonk": lambda p, cfg: PhonkGenerator(
        params=p,
        variant=cfg.get("variant", "classic_phonk"),
        cowbell_density=cfg.get("cowbell_density", 0.7),
        bass_slide_amount=cfg.get("bass_slide_amount", 5),
        filter_cutoff=cfg.get("filter_cutoff", 0.4),
        memphis_chops=cfg.get("memphis_chops", True),
        aggression=cfg.get("aggression", 0.6),
    ),
    "melodic_rap": lambda p, cfg: MelodicRapGenerator(
        params=p,
        variant=cfg.get("variant", "sing_rap"),
        repetition_factor=cfg.get("repetition_factor", 0.5),
        stepwise_bias=cfg.get("stepwise_bias", 0.7),
        bend_probability=cfg.get("bend_probability", 0.15),
        phrase_length=cfg.get("phrase_length", 4.0),
        rest_probability=cfg.get("rest_probability", 0.25),
        octave_register=cfg.get("octave_register", 5),
    ),
    "uk_garage": lambda p, cfg: UKGarageGenerator(
        params=p,
        variant=cfg.get("variant", "2step"),
        shuffle_amount=cfg.get("shuffle_amount", 0.55),
        skippy_hats=cfg.get("skippy_hats", True),
        include_stabs=cfg.get("include_stabs", True),
        bass_wobble=cfg.get("bass_wobble", True),
        chop_density=cfg.get("chop_density", 0.3),
    ),
    "hyperpop": lambda p, cfg: HyperpopGenerator(
        params=p,
        variant=cfg.get("variant", "standard"),
        pitch_shift_range=cfg.get("pitch_shift_range", 12),
        glitch_density=cfg.get("glitch_density", 0.4),
        distortion_amount=cfg.get("distortion_amount", 0.5),
        chaos_factor=cfg.get("chaos_factor", 0.3),
        include_leads=cfg.get("include_leads", True),
    ),
    "advanced_step_seq": lambda p, cfg: AdvancedStepSequencer(
        params=p,
        pattern=cfg.get("pattern", "four_on_floor"),
        steps=cfg.get("steps", 16),
        humanize_timing=cfg.get("humanize_timing", 0.02),
        humanize_velocity=cfg.get("humanize_velocity", 8),
        swing=cfg.get("swing", 0.5),
    ),
    "bpm_adaptive": lambda p, cfg: BPMAdaptiveGenerator(
        params=p,
        bpm=cfg.get("bpm", 120.0),
        reference_bpm=cfg.get("reference_bpm", 120.0),
        scaling_mode=cfg.get("scaling_mode", "logarithmic"),
        min_density=cfg.get("min_density", 0.3),
        max_density=cfg.get("max_density", 1.5),
    ),
    "genre_fusion": lambda p, cfg: GenreFusionEngine(
        params=p,
        genre_a=cfg.get("genre_a", "trap"),
        genre_b=cfg.get("genre_b", "jazz"),
        blend_ratio=cfg.get("blend_ratio", 0.5),
        fusion_mode=cfg.get("fusion_mode", "interleave"),
        morph_steps=cfg.get("morph_steps", 8),
    ),
    "vocal_melody_auto": lambda p, cfg: VocalMelodyAutoGenerator(
        params=p,
        variant=cfg.get("variant", "travis"),
        register=cfg.get("register", "mid"),
        sustain_preference=cfg.get("sustain_preference", 0.5),
        octave_jump_probability=cfg.get("octave_jump_probability", 0.15),
        grace_note_probability=cfg.get("grace_note_probability", 0.2),
        repetition_amount=cfg.get("repetition_amount", 0.4),
    ),
    "jersey_club": lambda p, cfg: JerseyClubGenerator(
        params=p,
        variant=cfg.get("variant", "classic"),
        kick_triplet_density=cfg.get("kick_triplet_density", 0.7),
        stutter_breaks=cfg.get("stutter_breaks", True),
        chopped_samples=cfg.get("chopped_samples", True),
        birdman_sample=cfg.get("birdman_sample", False),
    ),
    "dembow": lambda p, cfg: DembowGenerator(
        params=p,
        variant=cfg.get("variant", "classic"),
        shaker_density=cfg.get("shaker_density", 0.7),
        include_bass=cfg.get("include_bass", True),
        cowbell_accent=cfg.get("cowbell_accent", True),
        swing_amount=cfg.get("swing_amount", 0.1),
    ),
    "baile_funk": lambda p, cfg: BaileFunkGenerator(
        params=p,
        variant=cfg.get("variant", "classic"),
        bass_distortion=cfg.get("bass_distortion", 0.7),
        percussion_density=cfg.get("percussion_density", 0.6),
        mc_chops=cfg.get("mc_chops", True),
        slide_amount=cfg.get("slide_amount", 7),
    ),
    "rage_beat": lambda p, cfg: RageBeatGenerator(
        params=p,
        variant=cfg.get("variant", "carti"),
        synth_distortion=cfg.get("synth_distortion", 0.8),
        hat_speed=cfg.get("hat_speed", "sixteenth"),
        aggression=cfg.get("aggression", 0.7),
        include_synth_lead=cfg.get("include_synth_lead", True),
    ),
    "pluggnb": lambda p, cfg: PluggnbGenerator(
        params=p,
        variant=cfg.get("variant", "pluggnb"),
        pad_voicing=cfg.get("pad_voicing", "ninth"),
        include_808=cfg.get("include_808", True),
        hat_style=cfg.get("hat_style", "gentle"),
        melody_register=cfg.get("melody_register", 5),
    ),
    "latin_trap": lambda p, cfg: LatinTrapGenerator(
        params=p,
        variant=cfg.get("variant", "reggaeton_trap"),
        dembow_influence=cfg.get("dembow_influence", 0.6),
        hat_rolls=cfg.get("hat_rolls", True),
        include_percussion=cfg.get("include_percussion", True),
    ),
    "cloud_rap": lambda p, cfg: CloudRapGenerator(
        params=p,
        variant=cfg.get("variant", "cloud"),
        pad_density=cfg.get("pad_density", 0.6),
        drum_sparseness=cfg.get("drum_sparseness", 0.5),
        arp_speed=cfg.get("arp_speed", "slow"),
    ),
    "dnb_jungle": lambda p, cfg: DnBJungleGenerator(
        params=p,
        variant=cfg.get("variant", "liquid"),
        break_density=cfg.get("break_density", 0.6),
        reese_amount=cfg.get("reese_amount", 0.5),
        sub_weight=cfg.get("sub_weight", 0.7),
    ),
    "hardstyle": lambda p, cfg: HardstyleGenerator(
        params=p,
        variant=cfg.get("variant", "euphoric"),
        kick_distortion=cfg.get("kick_distortion", 0.8),
        include_lead=cfg.get("include_lead", True),
        reverse_bass_weight=cfg.get("reverse_bass_weight", 0.5),
    ),
    "synthwave": lambda p, cfg: SynthwaveGenerator(
        params=p,
        variant=cfg.get("variant", "outrun"),
        arp_pattern=cfg.get("arp_pattern", "up"),
        gated_pads=cfg.get("gated_pads", True),
        include_lead=cfg.get("include_lead", True),
        gate_rate=cfg.get("gate_rate", 0.5),
    ),
    "boom_bap": lambda p, cfg: BoomBapGenerator(
        params=p,
        variant=cfg.get("variant", "classic"),
        swing_ratio=cfg.get("swing_ratio", 0.58),
        chop_density=cfg.get("chop_density", 0.4),
        ghost_snares=cfg.get("ghost_snares", True),
        dusty_velocities=cfg.get("dusty_velocities", True),
    ),
    "future_bass": lambda p, cfg: FutureBassGenerator(
        params=p,
        variant=cfg.get("variant", "standard"),
        chord_chop_rate=cfg.get("chord_chop_rate", 0.5),
        sidechain_feel=cfg.get("sidechain_feel", True),
        include_vocal_chops=cfg.get("include_vocal_chops", True),
        supersaw_voices=cfg.get("supersaw_voices", 5),
    ),
    "grime": lambda p, cfg: GrimeGenerator(
        params=p,
        variant=cfg.get("variant", "classic"),
        synth_aggression=cfg.get("synth_aggression", 0.7),
        include_melody=cfg.get("include_melody", True),
    ),
    "witch_house": lambda p, cfg: WitchHouseGenerator(
        params=p,
        variant=cfg.get("variant", "classic"),
        slowdown_factor=cfg.get("slowdown_factor", 0.5),
        pad_darkness=cfg.get("pad_darkness", 0.8),
    ),
    "phonk_house": lambda p, cfg: PhonkHouseGenerator(
        params=p,
        variant=cfg.get("variant", "drift_house"),
        cowbell_density=cfg.get("cowbell_density", 0.6),
        bass_slides=cfg.get("bass_slides", True),
    ),
    "amapiano_logdrum": lambda p, cfg: AmapianoLogDrumGenerator(
        params=p,
        pattern=cfg.get("pattern", "classic"),
        pitch_variation=cfg.get("pitch_variation", 0.4),
        velocity_humanize=cfg.get("velocity_humanize", 0.3),
        ghost_probability=cfg.get("ghost_probability", 0.2),
        swing=cfg.get("swing", 0.55),
        note_length_variation=cfg.get("note_length_variation", 0.3),
    ),
    "afro_percussion": lambda p, cfg: AfroPercussionGenerator(
        params=p,
        ensemble=cfg.get("ensemble", "west_african"),
        density=cfg.get("density", 0.6),
        include_pitched=cfg.get("include_pitched", True),
        call_response=cfg.get("call_response", True),
        swing=cfg.get("swing", 0.55),
    ),
    "highlife_guitar": lambda p, cfg: HighlifeGuitarGenerator(
        params=p,
        variant=cfg.get("variant", "highlife"),
        riff_density=cfg.get("riff_density", 0.7),
        palm_mute_ratio=cfg.get("palm_mute_ratio", 0.3),
        octave_doubling=cfg.get("octave_doubling", True),
        interlocking=cfg.get("interlocking", False),
        pentatonic_bias=cfg.get("pentatonic_bias", 0.6),
    ),
    "afro_house": lambda p, cfg: AfroHouseGenerator(
        params=p,
        variant=cfg.get("variant", "deep"),
        percussion_density=cfg.get("percussion_density", 0.6),
        include_marimba=cfg.get("include_marimba", True),
        bass_depth=cfg.get("bass_depth", 0.7),
    ),
    "gqom": lambda p, cfg: GqomGenerator(
        params=p,
        variant=cfg.get("variant", "classic"),
        kick_weight=cfg.get("kick_weight", 0.8),
        include_vocal_stabs=cfg.get("include_vocal_stabs", True),
    ),
    "kuduro": lambda p, cfg: KuduroGenerator(
        params=p,
        variant=cfg.get("variant", "kuduro"),
        intensity=cfg.get("intensity", 0.7),
    ),
    "afro_drill": lambda p, cfg: AfroDrillGenerator(
        params=p,
        variant=cfg.get("variant", "burna"),
        slide_amount=cfg.get("slide_amount", 7),
        melody_density=cfg.get("melody_density", 0.6),
    ),
    "combat_escalation": lambda p, cfg: CombatEscalationGenerator(
        params=p,
        intensity=cfg.get("intensity", 0.5),
        layers=cfg.get("layers"),
        tempo_factor=cfg.get("tempo_factor", 1.0),
        key_change_on_climax=cfg.get("key_change_on_climax", True),
    ),
    "stinger": lambda p, cfg: StingerGenerator(
        params=p,
        stinger_type=cfg.get("stinger_type", "discovery"),
        root_note=cfg.get("root_note", 0),
        register=cfg.get("register", 5),
        velocity_multiplier=cfg.get("velocity_multiplier", 1.0),
        variation=cfg.get("variation", True),
    ),
    "chiptune": lambda p, cfg: ChiptuneGenerator(
        params=p,
        variant=cfg.get("variant", "nes_classic"),
        channels=cfg.get("channels"),
        duty_cycle=cfg.get("duty_cycle", "50%"),
        arpeggio_speed=cfg.get("arpeggio_speed", 0.125),
        melody_style=cfg.get("melody_style", "stepwise"),
    ),
    "horror_dissonance": lambda p, cfg: HorrorDissonanceGenerator(
        params=p,
        variant=cfg.get("variant", "psychological"),
        dissonance_level=cfg.get("dissonance_level", 0.7),
        silence_probability=cfg.get("silence_probability", 0.15),
        pitch_drift=cfg.get("pitch_drift", 0.3),
        density=cfg.get("density", 0.4),
    ),
    "stealth_state": lambda p, cfg: StealthStateGenerator(
        params=p,
        stealth_state=cfg.get("stealth_state", "hidden"),
        transition_speed=cfg.get("transition_speed", 0.5),
        heartbeat=cfg.get("heartbeat", True),
    ),
    "procedural_exploration": lambda p, cfg: ProceduralExplorationGenerator(
        params=p,
        variant=cfg.get("variant", "nature"),
        mood=cfg.get("mood", "peaceful"),
        loop_length_bars=cfg.get("loop_length_bars", 4),
        density=cfg.get("density", 0.35),
    ),
    "boss_battle": lambda p, cfg: BossBattleGenerator(
        params=p,
        phase=cfg.get("phase", "fight"),
        variant=cfg.get("variant", "epic"),
        choir_stabs=cfg.get("choir_stabs", True),
        brass_fanfare=cfg.get("brass_fanfare", True),
        timpani_drive=cfg.get("timpani_drive", True),
    ),
    "puzzle_loop": lambda p, cfg: PuzzleLoopGenerator(
        params=p,
        variant=cfg.get("variant", "bells"),
        complexity=cfg.get("complexity", 0.3),
        loop_bars=cfg.get("loop_bars", 4),
        register=cfg.get("register", "mid"),
    ),
    "medieval_tavern": lambda p, cfg: MedievalTavernGenerator(
        params=p,
        variant=cfg.get("variant", "tavern"),
        mode=cfg.get("mode", "dorian"),
        lute_density=cfg.get("lute_density", 0.7),
        include_flute=cfg.get("include_flute", True),
        dance_rhythm=cfg.get("dance_rhythm", True),
    ),
    "scifi_underscore": lambda p, cfg: SciFiUnderscoreGenerator(
        params=p,
        variant=cfg.get("variant", "blade_runner"),
        pad_density=cfg.get("pad_density", 0.6),
        arp_speed=cfg.get("arp_speed", 0.25),
        include_bass_synth=cfg.get("include_bass_synth", True),
    ),
    "victory_fanfare": lambda p, cfg: VictoryFanfareGenerator(
        params=p,
        variant=cfg.get("variant", "victory"),
        register=cfg.get("register", 5),
        dynamics=cfg.get("dynamics", "forte"),
    ),
    "strings_staccato": lambda p, cfg: StringsStaccatoGenerator(
        params=p,
        style=cfg.get("style", "octaves"),
        note_range_low=cfg.get("note_range_low"),
        note_range_high=cfg.get("note_range_high"),
    ),
    "hemiola": lambda p, cfg: HemiolaGenerator(
        params=p,
        pattern=cfg.get("pattern", "3_over_2"),
        pitch_strategy=cfg.get("pitch_strategy", "chord_tone"),
        velocity_accent=cfg.get("velocity_accent", 1.15),
        note_duration=cfg.get("note_duration"),
        cycles_per_chord=cfg.get("cycles_per_chord", 1),
    ),
    "backbeat": lambda p, cfg: BackbeatGenerator(
        params=p,
        mode=cfg.get("mode", "accent"),
        accent_velocity=cfg.get("accent_velocity", 1.0),
        ghost_velocity=cfg.get("ghost_velocity", 0.4),
        subdivision=cfg.get("subdivision", 1.0),
        pitch_strategy=cfg.get("pitch_strategy", "chord_tone"),
    ),
    "chord_voicing": lambda p, cfg: ChordVoicingGenerator(
        params=p,
        voicing=cfg.get("voicing", "drop2"),
        rhythm_pattern=cfg.get("rhythm_pattern", "sustained"),
        octave=cfg.get("octave", 4),
        velocity_curve=cfg.get("velocity_curve", "flat"),
    ),
    "dynamics": lambda p, cfg: DynamicsCurveGenerator(
        params=p,
        curve_type=cfg.get("curve_type", "crescendo"),
        note_duration=cfg.get("note_duration", 1.0),
        pitch_strategy=cfg.get("pitch_strategy", "chord_tone"),
        strength=cfg.get("strength", 1.0),
    ),
    "secondary_dominant": lambda p, cfg: SecondaryDominantGenerator(
        params=p,
        strategy=cfg.get("strategy", "secondary"),
        voicing=cfg.get("voicing", "root_position"),
        octave=cfg.get("octave", 4),
    ),
    "section_builder": lambda p, cfg: SectionBuilderGenerator(
        params=p,
        section_type=cfg.get("section_type", "verse"),
        pattern=cfg.get("pattern", "melody"),
        bars_per_section=cfg.get("bars_per_section", 4),
    ),
    "transition": lambda p, cfg: TransitionGenerator(
        params=p,
        transition_type=cfg.get("transition_type", "build"),
        length_beats=cfg.get("length_beats", 8.0),
        octave_range=cfg.get("octave_range", 2),
        rhythm_acceleration=cfg.get("rhythm_acceleration", 1.0),
    ),
    "swing": lambda p, cfg: SwingGenerator(
        params=p,
        swing_ratio=cfg.get("swing_ratio", 0.67),
        subdivision=cfg.get("subdivision", 0.5),
        pitch_strategy=cfg.get("pitch_strategy", "chord_tone"),
        accent_pattern=cfg.get("accent_pattern", "downbeat"),
    ),
    "downbeat_rest": lambda p, cfg: DownbeatRestGenerator(
        params=p,
        mode=cfg.get("mode", "skip"),
        delay_amount=cfg.get("delay_amount", 0.5),
        caesura_length=cfg.get("caesura_length", 1.0),
        subdivision=cfg.get("subdivision", 1.0),
        pitch_strategy=cfg.get("pitch_strategy", "chord_tone"),
    ),
    "dark_pad": lambda p, cfg: DarkPadGenerator(
        params=p,
        mode=cfg.get("mode", "minor_pad"),
        chord_dur=cfg.get("chord_dur", 8.0),
        velocity_level=cfg.get("velocity_level", 0.35),
        register=cfg.get("register", "low"),
        overlap=cfg.get("overlap", 0.3),
    ),
    "tension": lambda p, cfg: TensionGenerator(
        params=p,
        mode=cfg.get("mode", "semitone_cluster"),
        note_duration=cfg.get("note_duration", 2.0),
        velocity_level=cfg.get("velocity_level", 0.4),
        register=cfg.get("register", "mid"),
    ),
    "dark_bass": lambda p, cfg: DarkBassGenerator(
        params=p,
        mode=cfg.get("mode", "doom"),
        octave=cfg.get("octave", 2),
        note_duration=cfg.get("note_duration", 4.0),
        velocity_level=cfg.get("velocity_level", 0.7),
        movement=cfg.get("movement", "root_only"),
    ),
    "bass_808_sliding": lambda p, cfg: Bass808SlidingGenerator(
        params=p,
        pattern=cfg.get("pattern", "trap_basic"),
        slide_type=cfg.get("slide_type", "overlap"),
        slide_probability=cfg.get("slide_probability", 0.4),
        octave_range=cfg.get("octave_range", 2),
        accent_velocity=cfg.get("accent_velocity", 1.1),
        ghost_velocity_ratio=cfg.get("ghost_velocity_ratio", 0.55),
    ),
    "hihat_stutter": lambda p, cfg: HiHatStutterGenerator(
        params=p,
        pattern=cfg.get("pattern", "trap_eighth"),
        roll_density=cfg.get("roll_density", 0.4),
        open_hat_probability=cfg.get("open_hat_probability", 0.15),
        velocity_accent=cfg.get("velocity_accent", True),
        pitch_variation=cfg.get("pitch_variation", True),
        stutter_lengths=cfg.get("stutter_lengths"),
        instrument=cfg.get("instrument", "hh_closed"),
    ),
    "drill_pattern": lambda p, cfg: DrillPatternGenerator(
        params=p,
        variant=cfg.get("variant", "uk_drill"),
        slide_amount=cfg.get("slide_amount", 7),
        stutter_intensity=cfg.get("stutter_intensity", 0.5),
        snare_displacement=cfg.get("snare_displacement", 1),
        include_piano=cfg.get("include_piano", True),
    ),
    "ghost_notes": lambda p, cfg: GhostNotesGenerator(
        params=p,
        target=cfg.get("target", "snare"),
        pattern=cfg.get("pattern", "funk"),
        ghost_velocity=cfg.get("ghost_velocity", 35),
        ghost_density=cfg.get("ghost_density", 0.6),
        placement=cfg.get("placement", "sixteenth"),
    ),
}
